

export const DemoMemoObject = {
    0: {"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Hello there. This is a calendar where each day is a memo."}]}]},
    1: {"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"You can loosely write down stuff for each day."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Buy Groceries"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Email Marty"}]}]}]}]},
    2: {"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"You can add time stamps too. Write @13.3-15{space}, and"}]},{"type":"paragraph","content":[{"type":"timeRange","attrs":{"timeRange":"@13:30~15:00"}},{"type":"text","text":"Dentist Appointment"}]}]},
    3: {"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"More stamps too."}]},{"type":"paragraph","content":[{"type":"text","text":"@am{space} "},{"type":"timeRange","attrs":{"timeRange":"@AM"}},{"type":"text","text":" Try PM for yourself!"}]},{"type":"paragraph","content":[{"type":"text","text":"@all{space} "},{"type":"timeRange","attrs":{"timeRange":"@AllDay"}}]}]},
    4: {"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"If you're on desktop, hotkeys are useful."}]},{"type":"paragraph","content":[{"type":"text","text":"On the main page, press F. It will take you to the Friday memo."}]}]},
    5: {"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Did you get here by pressing F? Good job!"}]},{"type":"paragraph","content":[{"type":"text","text":"If you want to go back, press B."}]}]},
    6: {"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"If you want to learn more:"}]},{"type":"paragraph","content":[{"type":"text","text":"Timestamps and syntax -- "},{"type":"text","marks":[{"type":"link","attrs":{"href":"https://loosecal.com/editor","target":"_blank","rel":"noopener noreferrer nofollow","class":null}}],"text":"https://loosecal.com/editor"}]},{"type":"paragraph","content":[{"type":"text","text":"Hotkeys -- "},{"type":"text","marks":[{"type":"link","attrs":{"href":"https://loosecal.com/hotkeys","target":"_blank","rel":"noopener noreferrer nofollow","class":null}}],"text":"https://loosecal.com/hotkeys"}]},{"type":"paragraph"}]},
}